config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :casefiles
  resources :clients
  resources :tasks
  resources :users
  root 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:for, :date, :time, :caller_name, :caller_of, :phone_number, :phone_message, :call_taker)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :for %>
    <%= f.input :date %>
    <%= f.input :time %>
    <%= f.input :caller_name %>
    <%= f.input :caller_of %>
    <%= f.input :phone_number %>
    <%= f.input :phone_message %>
    <%= f.input :call_taker %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Phone Messages</h1>

<table class="table">
  <thead>
    <tr>
      <th>For</th>
      <th>Date</th>
      <th>Time</th>
      <th>Caller name</th>
      <th>Caller of</th>
      <th>Phone number</th>
      <th>Phone message</th>
      <th>Call taker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.for %></td>
        <td><%= message.date %></td>
        <td><%= message.time %></td>
        <td><%= message.caller_name %></td>
        <td><%= message.caller_of %></td>
        <td><%= message.phone_number %></td>
        <td><%= message.phone_message %></td>
        <td><%= message.call_taker %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>For:</strong>
  <%= @message.for %>
</p>

<p>
  <strong>Date:</strong>
  <%= @message.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @message.time %>
</p>

<p>
  <strong>Caller name:</strong>
  <%= @message.caller_name %>
</p>

<p>
  <strong>Caller of:</strong>
  <%= @message.caller_of %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @message.phone_number %>
</p>

<p>
  <strong>Phone message:</strong>
  <%= @message.phone_message %>
</p>

<p>
  <strong>Call taker:</strong>
  <%= @message.call_taker %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>