config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :casefiles
  resources :clients
  resources :tasks
  resources :users
  root 'home#index'

end

app/models/casefile.rb
class Casefile < ActiveRecord::Base
end

app/controllers/casefiles_controller.rb
class CasefilesController < ApplicationController
  before_action :set_casefile, only: [:show, :edit, :update, :destroy]

  # GET /casefiles
  # GET /casefiles.json
  def index
    @casefiles = Casefile.all
  end

  # GET /casefiles/1
  # GET /casefiles/1.json
  def show
  end

  # GET /casefiles/new
  def new
    @casefile = Casefile.new
  end

  # GET /casefiles/1/edit
  def edit
  end

  # POST /casefiles
  # POST /casefiles.json
  def create
    @casefile = Casefile.new(casefile_params)

    respond_to do |format|
      if @casefile.save
        format.html { redirect_to @casefile, notice: 'Casefile was successfully created.' }
        format.json { render :show, status: :created, location: @casefile }
      else
        format.html { render :new }
        format.json { render json: @casefile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casefiles/1
  # PATCH/PUT /casefiles/1.json
  def update
    respond_to do |format|
      if @casefile.update(casefile_params)
        format.html { redirect_to @casefile, notice: 'Casefile was successfully updated.' }
        format.json { render :show, status: :ok, location: @casefile }
      else
        format.html { render :edit }
        format.json { render json: @casefile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casefiles/1
  # DELETE /casefiles/1.json
  def destroy
    @casefile.destroy
    respond_to do |format|
      format.html { redirect_to casefiles_url, notice: 'Casefile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casefile
      @casefile = Casefile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casefile_params
      params.require(:casefile).permit(:client, :matter, :file_number, :date_opened, :date_closed, :location)
    end
end

app/helpers/casefiles_helper.rb
module CasefilesHelper
end

app/views/casefiles/_form.html.erb
<%= simple_form_for(@casefile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :client %>
    <%= f.input :matter %>
    <%= f.input :file_number %>
    <%= f.input :date_opened %>
    <%= f.input :date_closed %>
    <%= f.input :location %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/casefiles/edit.html.erb
<h1>Editing Casefile</h1>

<%= render 'form' %>

<%= link_to 'Show', @casefile %> |
<%= link_to 'Back', casefiles_path %>

app/views/casefiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Case Files</h1>

<p>Use CTRL+F to search for a file.</p>

<table class="table">
  <thead>
    <tr>
      <th>Client</th>
      <th>Matter</th>
      <th>File number</th>
      <th>Date opened</th>
      <th>Date closed</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casefiles.each do |casefile| %>
      <tr>
        <td><%= casefile.client %></td>
        <td><%= casefile.matter %></td>
        <td><%= casefile.file_number %></td>
        <td><%= casefile.date_opened %></td>
        <td><%= casefile.date_closed %></td>
        <td><%= casefile.location %></td>
        <td><%= link_to 'Show', casefile %></td>
        <td><%= link_to 'Edit', edit_casefile_path(casefile) %></td>
        <td><%= link_to 'Destroy', casefile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'close', close_casefile_path(casefile) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Casefile', new_casefile_path %>

app/views/casefiles/new.html.erb
<h1>Enter New Case</h1>

<%= simple_form_for(@casefile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :client %>
    <%= f.input :matter %>
    <%= f.input :file_number %>
    <%= f.input :date_opened %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


<%= link_to 'Back', casefiles_path %>

app/views/casefiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @casefile.client %>
</p>

<p>
  <strong>Matter:</strong>
  <%= @casefile.matter %>
</p>

<p>
  <strong>File number:</strong>
  <%= @casefile.file_number %>
</p>

<p>
  <strong>Date opened:</strong>
  <%= @casefile.date_opened %>
</p>

<p>
  <strong>Date closed:</strong>
  <%= @casefile.date_closed %>
</p>

<p>
  <strong>Location:</strong>
  <%= @casefile.location %>
</p>

<%= link_to 'Edit', edit_casefile_path(@casefile) %> |
<%= link_to 'Back', casefiles_path %>